Spelling and styling fixes, unused code reused, and more documentation added.
codice/usng4j pull request #10
Opened 2018-11-15 18:37 UTC by dimitry-sherman

#### What does this PR do?
Spelling and styling fixes, unused code reused, and more documentation added.

#### Who is reviewing it? 
@millerw8
@Lambeaux
@Variadicism
@samuelechu

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@stustison
@dcruver

#### How should this be tested? (List steps with links to updated documentation)
All the necessary unit tests have been added and pass, all the legacy unit tests pass as well.
**Modified code code coverage:**
CoordinateSystemTranslatorImpl  |  Method - 80% (28/ 35)  |  Line - 84% (310/ 368)
**Added code code coverage:**
UtmUpsCoordinateImpl  |  Method - 100% (28/ 28)  |  Line - 100% (93/ 93)

#### Any background context you want to provide?
Added UPS functionality to `usng4j` library for parity wiht `usng.js` where the functionality was already added.
#### What are the relevant tickets?
[DDF-4323](https://codice.atlassian.net/browse/DDF-4323)
#### Screenshots (if appropriate)
#### Checklist:
- [x] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

2018-11-15 19:24 UTC, coyotesqrl approved these changes

2018-11-15 22:14 UTC, Schachte approved these changes

2018-11-19 19:05 UTC, dcruver requested changes

2018-11-19 19:05 UTC, dcruver commented on usng4j-impl/src/test/java/org/codice/usng4j/impl/BaseClassForUsng4jTest.java
> +    // TODO Issue 9: add a set of valid and invalid UTM coordinates test data
```suggestion
    // TODO https://github.com/codice/usng4j/issues/9: add a set of valid and invalid UTM coordinates test data
```

2018-11-19 19:05 UTC, dcruver commented on usng4j-impl/src/test/java/org/codice/usng4j/impl/UtmUpsCoordinateImplTest.java
> +  // TODO Issue 9: implement the UTM parsing tests,
```suggestion
  // TODO https://github.com/codice/usng4j/issues/9: implement the UTM parsing tests,
```

2018-11-19 19:28 UTC, Variadicism-zz approved these changes

2018-11-20 15:05 UTC, dcruver approved these changes

2018-11-20 15:41 UTC, merged